apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: data-pass-example-
spec:
  entrypoint: ndarray-pass-sharedvol

  volumeClaimTemplates:                   # define pvc
  - metadata:
      name: shareddir
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 128Ki
        limits:
          storage: 128Ki

  templates:
  - name: ndarray-pass-sharedvol
    steps:
      - - name: produce-step
          template: produce-test-data
      - - name: consume-step
          template: consume-test-data

  - name: produce-test-data
    container:
      image: quay.io/kachau/produce_prom_testdata:dev
      volumeMounts:                       # mount shared volume
      - name: shareddir
        mountPath: /mnt/vol

  - name: consume-test-data
    container:
      image: quay.io/kachau/consume_prom_testdata:dev
      volumeMounts:                       # mount shared volume
        - name: shareddir
          mountPath: /mnt/vol
